### PR TITLE
Accept proxy options for the IDAM test harness as required

### PR DESCRIPTION
**Pull request by tchow8**
IDAM Test Harness fails to create or remove users if done locally, as the requests are attempted without proxy. This is because CodeceptJS is passed a proxy via its own parameters --proxy-server and this won't be passed through to the IDAM test harness.

### CODE REVIEW

**Review by dtaylor7 — COMMENTED** [review]
Does this work when running tests CNP?

**Comment by tchow8** [comment]
Honestly haven't tried. Should be safe to merge still assuming our current package.json won't pick up a version change to 1.1.0. Then can open a preview env with 1.1.0 to test.

**Review by dtaylor7 — CHANGES_REQUESTED** [review]
My suggestion would be to create a new PR with the package.json referencing this commit to test the changes work correct on build e.g.:
```
"devDependencies": {
   "@hmcts/div-idam-express-middleware": "https://github.com/hmcts/div-idam-express-middleware#f59c03bfb3b39bde0c1f93c740262723ecb4108b",
   ...
}
```

**Comment by Rob-Doherty** [comment]
Have tested this locally as suggested @dtaylor7 and it works - will need a slight code change on frontend as well, but will add that to a new div-pet-frontend PR, but will create that once this PR is merged 👍

**Review by Rob-Doherty — APPROVED** [review]
👍

**Review by dtaylor7 — APPROVED** [review]

**Pull request merged**
